#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
