#!/usr/bin/env bash                                                             
# Bash script that configures an Nginx server so that redirect_me           

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "server {
      listen 80;
      root   /etc/nginx/html;
      index  index.html;
      location /redirect_me {
        return 301 www.linkedin.com;
      }
}" > /etc/nginx/sites-available/default
sudo service nginx restart

