#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 350106-web-01 100.25.188.65:80 check\n\tserver 350106-web-02 34.204.61.68:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
